DB_HOST = '192.168.1.2'
DB_CONTACT_POINTS = [DB_HOST]
DB_KEYSPACE = 'hello'
# DB_KEYSPACE = 'test'
# DB_KEYSPACE = 'test_dw'
DB_USER = 'gtsb'
DB_PASSWORD = 'gtsb'
DB_SPLIT_SIZE_IN_MB = 128
DB_TBL_METRIC = 'tbl_hello_world'
